server:
  port: 7513

# eureka（集群）注册地址，这里会将服务实例注册到eureka集群服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/,http://localhost:10087/eureka/
    # 是否注册进注册中心 默认true
    register-with-eureka: true
    # 是否去拉取
    fetch-registry: true
    # 多久去拉取一次可用服务列表
    registry-fetch-interval-seconds: 5

product1: #指定负载均衡算法 服务提供的服务名  这里指定随机算法
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

# 注册进eureka的唯一服务名
spring:
  application:
    name: customer1

